### PR TITLE
update docs and logos on teacher interface

### PR DESCRIPTION
**Pull request by jganseman**
Also updated the session expired message.

### CODE REVIEW

**Comment by smadbe** [comment]
Please split into two commits. For the logos, it has to be checked more in details on a local instance, it will be maybe for later. While the other change must be deployed asap I assume.

**Comment by jganseman** [comment]
Split up in several commits.

**Comment by smadbe** [comment]
ah you run it in docker now ? maybe ok then..

**Comment by smadbe** [comment]
And your first commit with everything is still there. I don't know how you do that ;-)  
No worries...  :-)

**Review by smadbe — APPROVED** [review]

**Pull request merged**
